services:
  authorization-microservice-db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorization_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
