spring:
  datasource:
    url: jdbc:postgresql://authorization-microservice-db:5432/authorization_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://authorization-microservice-db:5432/authorization_db
    user: postgres
    password: postgres

jwt:
  private:
    key:
      path: keys/privateSortlyQR.pem
  public:
    key:
      path: keys/publicSortlyQR.pem

server:
  port: 8080