spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authorization_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/authorization_db
    user: postgres
    password: postgres

jwt:
  private:
    key:
      path: keys/privateSortlyQR.pem
  public:
    key:
      path: keys/publicSortlyQR.pem

server:
  port: 8081
